config/routes.rb
# -*- encoding : utf-8 -*-
BifWriting::Application.routes.draw do
  resources :passages
  root to: 'static_pages#home'
end

app/models/passage.rb
# -*- encoding : utf-8 -*-
class Passage < ActiveRecord::Base
  attr_accessible :passage
end

app/models/word.rb
# -*- encoding : utf-8 -*-
class Word < ActiveRecord::Base
  attr_accessible :rank, :word, :lemma, :pos, :pos_long, :english_definition, :frequency, :sum_frequency, :coca_spoken_freq, :coca_fiction_freq, :coca_magazines_freq, :coca_newspapers_freq, :sat, :gre
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/passages_controller.rb
# -*- encoding : utf-8 -*-
class PassagesController < ApplicationController
  include PassagesHelper
  def new
    @passage = Passage.new
  end

  def create
    @passage = Passage.new(params[:passage])
    if @passage.save
      redirect_to @passage
    else
      render :new
    end
  end

  def edit
    @passage = Passage.find(params[:id])
  end

  def update
    @passage = Passage.find(params[:id])
    if @passage.update_attributes(params[:passage])
      redirect_to @passage
    else
      render 'edit'
    end
  end

  def show
    @passage = Passage.find(params[:id])
    tokenizer = Punkt::SentenceTokenizer.new(@passage.passage)
    tgr = EngTagger.new
    # - Student time to produce a given writing passage
    # - Number of paragraphs
    # - Number of sentences
    # - Number of words
    # - Number of characters
    # - Average length of sentence (# of words)
    # - Average length of a paragraph (# of sentences)
    # - Frequency (using our corpus) of words used in the passage
    # - Originality score (compare words used to other users)
    # - Number of repeated words in the passage
    # - POS breakdown - number of nouns, verbs, etc.


    @total_characters = @passage.passage.length
   
    @total_characters_nonspaces = @passage.passage.gsub(/\s+/, '').length
   
    @paragraph_count = @passage.passage.split(/\n\n/).length

    # - Number of sentences
    @num_sentences_punkt = tokenizer.sentences_from_text(@passage.passage, :output => :tokenized_sentences).length
    @num_sentences_tagger = tgr.get_sentences(@passage.passage).length

    tagged_hash = tgr.add_tags_hash(@passage.passage)

    # - Number of words
    @num_words_tagger = tagged_hash.length
    @num_words_punkt = tokenizer.sentences_from_text(@passage.passage, :output => :tokenized_sentences).flatten!.length
    @num_words = @passage.passage.split.size

    # - Number of paragraphs

    @tag_hash = tgr.add_tags_hash(@passage.passage)
    @tagged_hash = tagged_hash.each { |k, v| tagged_hash[k] = pos_convert(v) }
    tagged_hash_values = @tagged_hash.values
    counts = Hash.new(0)
    tagged_hash_values.each { |v| counts[v] += 1 }
    @pos_count = counts
    # words = 314 (pages)
    # words = 312 (word)
    # words = 317 (word count tool)
    # words = 319 (wordcounter.net)
    # words = 320 (word count tool)
    # words = 313
    # sentences = 14
    # avg sentence length = 23
    # paragraphs = 8
    # characters (with spaces) = 1887
    # characters (without spaces) = 1582


    @freq_array = @tagged_hash.inject({}) { |h, (k, v)| h[k] = Word.where('word = ?', k).where("pos_long = ?", v).sum("frequency"); h }


    # Get all nouns from a tagged output
    @nouns = tgr.get_nouns(@tagged)
  
    #=> {"cat"=>1, "Alice"=>1}

    # Get all proper nouns
    @proper = tgr.get_proper_nouns(@tagged)

    #=> {"Alice"=>1}
  


  end

  def index
    @passages = Passage.order("id").all
  end

  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy
      redirect_to passages_path
  end

end

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController

  def home
  	text = "A minute is a unit of measurement of time or of angle. The minute is a unit of time equal to 1/60th of an hour or 60 seconds by 1. In the UTC time scale, a minute occasionally has 59 or 61 seconds; see leap second. The minute is not an SI unit; however, it is accepted for use with SI units. The symbol for minute or minutes is min. The fact that an hour contains 60 minutes is probably due to influences from the Babylonians, who used a base-60 or sexagesimal counting system. Colloquially, a min. may also refer to an indefinite amount of time substantially longer than the standardized length." 
  	tokenizer = Punkt::SentenceTokenizer.new(text)
	#@result = tokenizer.sentences_from_text(text, :output => :tokenized_sentences)
	#@result = tokenizer.sentences_from_text(text)
	#@result = tokenizer.sentences_from_text(text, :output => :sentences_text)

	# Create a parser object
  	tgr = EngTagger.new
  
  	# Sample text
  	text = "A minute is a unit of measurement of time or of angle. The minute is a unit of time equal to 1/60th of an hour or 60 seconds by 1. In the UTC time scale, a minute occasionally has 59 or 61 seconds; see leap second. The minute is not an SI unit; however, it is accepted for use with SI units. The symbol for minute or minutes is min. The fact that an hour contains 60 minutes is probably due to influences from the Babylonians, who used a base-60 or sexagesimal counting system. Colloquially, a min. may also refer to an indefinite amount of time substantially longer than the standardized length." 

  	# Add part-of-speech tags to text
  	@tagged = tgr.add_tags(text)
	#=> "<nnp>Alice</nnp> <vbd>chased</vbd> <det>the</det> <jj>big</jj> <jj>fat</jj><nn>cat</nn> <pp>.</pp>"
  

    @sentences = tgr.get_sentences(text)
  	# Get all nouns from a tagged output
  	@nouns = tgr.get_nouns(@tagged)
  
  	#=> {"cat"=>1, "Alice"=>1}

  	# Get all proper nouns
  	@proper = tgr.get_proper_nouns(@tagged)

  	#=> {"Alice"=>1}
  
  end

end

app/controllers/words_controller.rb
# -*- encoding : utf-8 -*-
class WordsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(
        :hard_wrap => true, :filter_html => true, :safe_links_only => true),
        :no_intra_emphasis => true, :autolink => true, :strikethrough => true, :superscript => true)
    return markdown.render(text).html_safe
  end
end

app/helpers/passages_helper.rb
# -*- encoding : utf-8 -*-
module PassagesHelper
  def pos_convert(pos)
	case pos
  	  when "cc"
  	    return "conjunction"
  	  when "det", "pdt", "prp", "prps", "wdt", "wps"
  	  	return "determiner"
  	  when "ex"
  	  	return "existential there"
  	  when "fw"
  	  	return "foreign words"		
  	  when "pp", "ppc", "ppd", "ppl", "ppr", "pps", "lrb", "rrb"
  	  	return "punctuation"
      when "vb", "vbd", "vbg", "vbn", "vbp", "vbz", "md"
      	return "verb"
   	  when "rb", "rbr", "rbs", "rp", "wrb"
   	  	return "adverb"
  	  when "nn", "nnp", "nnps", "nns"
  	    return "noun"
      when "jj", "jjr", "jjs"
        return "adjective" 
      when "wp"
    	return "pronoun"
   	  when "sym", "ls"
   	    return "symbol"
   	  when "uh"
   	  	return "interjection" 
   	  when "pos"
   	  	return "possessive"
   	  when "in", "to"
   	  	return "preposition"
   	  when "cd"
   	  	return "number"
   	  else
   	  	return pos	
	end
  end
end  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BiF Writing</title>
  <%= localstorage_shim %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Junge' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>	
</body>
</html>

app/views/passages/_form.html.erb
<%= form_for @passage do |f| %>
  	Current word count: <span id="display_count">0</span>

  	<%= f.text_area :passage, :class => "text", :id => "passage_area", :placeholder => "Start your thoughts here...", :"data-persist" => "garlic", :onKeyUp=> "word_count(this.value, hidden_count)" %>

    <%= f.submit "Submit", :class => "m-btn purple" %>
<% end %>

app/views/passages/edit.html.erb
<%= render "form" %>

app/views/passages/index.html.erb
<% @passages.each do |passage| %>
	<%= link_to passage.id, passage %><br>
<% end %>

app/views/passages/new.html.erb
<h1>Topic: </h1>
<h2>Description: </h2>
<%= link_to(image_tag("bold.png", :alt => "Bold"), :remote => true) %>
<%= link_to(image_tag("italic.png", :alt => "Italics"), :remote => true) %>
<%= link_to(image_tag("underline.png", :alt => "Underline"), :remote => true) %>

<%= render "form" %>

app/views/passages/show.html.erb
<h1 class="text">
	<%= markdown(@passage.passage) %>
</h1>	
<br>
<br>
<%= @tagged_hash %>
<br>
<br>
<%= @pos_count %>
<br>
<br>
<%= @freq_array %>
<br>
<br>
<%= @tag_hash %><br>
<%= @tag_hash.length %>
<br>
<br>
<strong>Number of Sentences (Punkt):</strong> <%= @num_sentences_punkt %><br>
<strong>Number of Sentences (Tagger):</strong> <%= @num_sentences_tagger %><br>
<br>
<strong>Number of Words (Punkt):</strong>  <%= @num_words_punkt %><br>
<strong>Number of Words (Tagger):</strong> <%=  @num_words_tagger %><br>
<strong>Number of Words (Other):</strong> <%= @num_words %><br>
Paragraph count: <%= @paragraph_count %><br>

<%= @total_characters %><br>
<%= @total_characters_nonspaces %><br>
<%= link_to "Edit", edit_passage_path(@passage) %> | 
<%= link_to "Delete", @passage, confirm: "Are you sure?", method: :delete %> | 
<%= link_to "Back", passages_path %>

app/views/static_pages/home.html.erb
<%= link_to "New Passage", new_passage_path %>
<%= link_to "Index", passages_path %>

app/views/words/index.html.erb
<h1>Words#index</h1>
<p>Find me in app/views/words/index.html.erb</p>